-*- mode: org -*-

* [2016-12-16 Fri]
Okay, so this is just going to be like a developer diary sort of thing so I can
remember where I picked off when I come back to this... So maybe this is kind of
like day one or something. 

Anyway, I rethought of the system for collisions and things. I'm just going to
call it clipping from now on. That seems better to me, as it allows for me to
then call interactions between enemies collisions instead. And then that will
have attack consequences and things to it.

Working forward, I need some way for the circles to move nicely/interestingly on
the board, then I'll have to do the same thing for the blue guys. When I have
both the reds and the blues, then I can start thinking about damage and stats
and junk.

Thus:
- red movements
- blue (should be mostly the same as red; so shouldn't take long.)
- interactions between red and blue, so things like mean staring, attacking,
  general aggression, etc. Maybe I could toy around with speech bubbles and
  things.
